site_prefix: "http://ett.usersys.redhat.com/"
bugzilla_prefix: "https://bugzilla.redhat.com/show_bug.cgi?id="
bz_bug_creation_url_mocked: "http://mead.usersys.redhat.com/mead-bzbridge/bug/mock"
bz_bug_creation_url: "http://mead.usersys.redhat.com/mead-bzbridge/bug/"
bz_bug_query_url: "http://mead.usersys.redhat.com/mead-bzbridge/bug/"
mead_scheduler: "http://mead.usersys.redhat.com"
bz_bug_status_update_url: "/mead-bzbridge/bug/status/<id>?oneway=<oneway>"
bz_bug_status_update_url_mocked: "/mead-bzbridge/bug/status/<id>?oneway=<oneway>"
magic_bug_id: "966279"
errata_url: "http://rhn.redhat.com" # Replace this with correct Internal Errata URL.
