site_prefix: "http://ett.usersys.redhat.com/"
bugzilla_prefix: "https://bugzilla.redhat.com/show_bug.cgi?id="
bz_bug_creation_url: "http://mead.usersys.redhat.com/mead-bzbridge/bug/mock"
bz_bug_query_url: "http://mead.usersys.redhat.com/mead-bzbridge/bug/"